// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly dashboard: dashboard.ServiceClient
    public readonly integrations: integrations.ServiceClient
    public readonly scheduler: scheduler.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.dashboard = new dashboard.ServiceClient(base)
        this.integrations = new integrations.ServiceClient(base)
        this.scheduler = new scheduler.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { analyze as api_dashboard_analyze_analyze } from "~backend/dashboard/analyze";
import { exportAnalysis as api_dashboard_export_exportAnalysis } from "~backend/dashboard/export";
import {
    addMetricSource as api_dashboard_unified_metrics_addMetricSource,
    getMetricSources as api_dashboard_unified_metrics_getMetricSources,
    getUnifiedDashboard as api_dashboard_unified_metrics_getUnifiedDashboard,
    removeMetricSource as api_dashboard_unified_metrics_removeMetricSource
} from "~backend/dashboard/unified-metrics";
import { upload as api_dashboard_upload_upload } from "~backend/dashboard/upload";

export namespace dashboard {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addMetricSource = this.addMetricSource.bind(this)
            this.analyze = this.analyze.bind(this)
            this.exportAnalysis = this.exportAnalysis.bind(this)
            this.getMetricSources = this.getMetricSources.bind(this)
            this.getUnifiedDashboard = this.getUnifiedDashboard.bind(this)
            this.removeMetricSource = this.removeMetricSource.bind(this)
            this.upload = this.upload.bind(this)
        }

        /**
         * Adds a new metric source to the unified dashboard.
         */
        public async addMetricSource(params: RequestType<typeof api_dashboard_unified_metrics_addMetricSource>): Promise<ResponseType<typeof api_dashboard_unified_metrics_addMetricSource>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/unified-dashboard/sources`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_unified_metrics_addMetricSource>
        }

        /**
         * Analyzes uploaded report data using AI to generate insights and recommendations.
         */
        public async analyze(params: RequestType<typeof api_dashboard_analyze_analyze>): Promise<ResponseType<typeof api_dashboard_analyze_analyze>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_analyze_analyze>
        }

        /**
         * Exports analysis results in different formats for sharing.
         */
        public async exportAnalysis(params: RequestType<typeof api_dashboard_export_exportAnalysis>): Promise<ResponseType<typeof api_dashboard_export_exportAnalysis>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_export_exportAnalysis>
        }

        /**
         * Lists all available metric sources.
         */
        public async getMetricSources(params: RequestType<typeof api_dashboard_unified_metrics_getMetricSources>): Promise<ResponseType<typeof api_dashboard_unified_metrics_getMetricSources>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/unified-dashboard/sources/list`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_unified_metrics_getMetricSources>
        }

        /**
         * Retrieves unified dashboard data from all connected sources.
         */
        public async getUnifiedDashboard(params: RequestType<typeof api_dashboard_unified_metrics_getUnifiedDashboard>): Promise<ResponseType<typeof api_dashboard_unified_metrics_getUnifiedDashboard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/unified-dashboard`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_unified_metrics_getUnifiedDashboard>
        }

        /**
         * Removes a metric source from the unified dashboard.
         */
        public async removeMetricSource(params: { sourceId: string }): Promise<ResponseType<typeof api_dashboard_unified_metrics_removeMetricSource>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/unified-dashboard/sources/${encodeURIComponent(params.sourceId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_unified_metrics_removeMetricSource>
        }

        /**
         * Uploads a CSV or Excel file for analysis.
         */
        public async upload(params: RequestType<typeof api_dashboard_upload_upload>): Promise<ResponseType<typeof api_dashboard_upload_upload>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/upload`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_upload_upload>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    exchangeFacebookToken as api_integrations_facebook_ads_exchangeFacebookToken,
    getFacebookAccounts as api_integrations_facebook_ads_getFacebookAccounts,
    getFacebookAuthUrl as api_integrations_facebook_ads_getFacebookAuthUrl,
    getFacebookData as api_integrations_facebook_ads_getFacebookData
} from "~backend/integrations/facebook-ads";
import {
    exchangeAdsToken as api_integrations_google_ads_exchangeAdsToken,
    getAdsAccounts as api_integrations_google_ads_getAdsAccounts,
    getAdsAuthUrl as api_integrations_google_ads_getAdsAuthUrl,
    getAdsData as api_integrations_google_ads_getAdsData
} from "~backend/integrations/google-ads";
import {
    exchangeGAToken as api_integrations_google_analytics_exchangeGAToken,
    getGAAccounts as api_integrations_google_analytics_getGAAccounts,
    getGAAuthUrl as api_integrations_google_analytics_getGAAuthUrl,
    getGAData as api_integrations_google_analytics_getGAData
} from "~backend/integrations/google-analytics";
import {
    fetchData as api_integrations_integration_manager_fetchData,
    getPlatformConfigs as api_integrations_integration_manager_getPlatformConfigs
} from "~backend/integrations/integration-manager";

export namespace integrations {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.exchangeAdsToken = this.exchangeAdsToken.bind(this)
            this.exchangeFacebookToken = this.exchangeFacebookToken.bind(this)
            this.exchangeGAToken = this.exchangeGAToken.bind(this)
            this.fetchData = this.fetchData.bind(this)
            this.getAdsAccounts = this.getAdsAccounts.bind(this)
            this.getAdsAuthUrl = this.getAdsAuthUrl.bind(this)
            this.getAdsData = this.getAdsData.bind(this)
            this.getFacebookAccounts = this.getFacebookAccounts.bind(this)
            this.getFacebookAuthUrl = this.getFacebookAuthUrl.bind(this)
            this.getFacebookData = this.getFacebookData.bind(this)
            this.getGAAccounts = this.getGAAccounts.bind(this)
            this.getGAAuthUrl = this.getGAAuthUrl.bind(this)
            this.getGAData = this.getGAData.bind(this)
            this.getPlatformConfigs = this.getPlatformConfigs.bind(this)
        }

        /**
         * Exchanges authorization code for access tokens.
         */
        public async exchangeAdsToken(params: RequestType<typeof api_integrations_google_ads_exchangeAdsToken>): Promise<ResponseType<typeof api_integrations_google_ads_exchangeAdsToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-ads/token`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_ads_exchangeAdsToken>
        }

        /**
         * Exchanges authorization code for access tokens.
         */
        public async exchangeFacebookToken(params: RequestType<typeof api_integrations_facebook_ads_exchangeFacebookToken>): Promise<ResponseType<typeof api_integrations_facebook_ads_exchangeFacebookToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/facebook-ads/token`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_facebook_ads_exchangeFacebookToken>
        }

        /**
         * Exchanges authorization code for access tokens.
         */
        public async exchangeGAToken(params: RequestType<typeof api_integrations_google_analytics_exchangeGAToken>): Promise<ResponseType<typeof api_integrations_google_analytics_exchangeGAToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-analytics/token`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_analytics_exchangeGAToken>
        }

        /**
         * Fetches data from integrated platforms and stores it for analysis.
         */
        public async fetchData(params: RequestType<typeof api_integrations_integration_manager_fetchData>): Promise<ResponseType<typeof api_integrations_integration_manager_fetchData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/integrations/fetch-data`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_integration_manager_fetchData>
        }

        /**
         * Fetches available Google Ads accounts.
         */
        public async getAdsAccounts(params: RequestType<typeof api_integrations_google_ads_getAdsAccounts>): Promise<ResponseType<typeof api_integrations_google_ads_getAdsAccounts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-ads/accounts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_ads_getAdsAccounts>
        }

        /**
         * Initiates Google Ads OAuth flow.
         */
        public async getAdsAuthUrl(params: RequestType<typeof api_integrations_google_ads_getAdsAuthUrl>): Promise<ResponseType<typeof api_integrations_google_ads_getAdsAuthUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-ads/auth`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_ads_getAdsAuthUrl>
        }

        /**
         * Fetches Google Ads data for analysis.
         */
        public async getAdsData(params: RequestType<typeof api_integrations_google_ads_getAdsData>): Promise<ResponseType<typeof api_integrations_google_ads_getAdsData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-ads/data`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_ads_getAdsData>
        }

        /**
         * Fetches available Facebook Ads accounts.
         */
        public async getFacebookAccounts(params: RequestType<typeof api_integrations_facebook_ads_getFacebookAccounts>): Promise<ResponseType<typeof api_integrations_facebook_ads_getFacebookAccounts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/facebook-ads/accounts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_facebook_ads_getFacebookAccounts>
        }

        /**
         * Initiates Facebook Ads OAuth flow.
         */
        public async getFacebookAuthUrl(params: RequestType<typeof api_integrations_facebook_ads_getFacebookAuthUrl>): Promise<ResponseType<typeof api_integrations_facebook_ads_getFacebookAuthUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/facebook-ads/auth`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_facebook_ads_getFacebookAuthUrl>
        }

        /**
         * Fetches Facebook Ads data for analysis.
         */
        public async getFacebookData(params: RequestType<typeof api_integrations_facebook_ads_getFacebookData>): Promise<ResponseType<typeof api_integrations_facebook_ads_getFacebookData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/facebook-ads/data`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_facebook_ads_getFacebookData>
        }

        /**
         * Fetches available Google Analytics accounts and properties.
         */
        public async getGAAccounts(params: RequestType<typeof api_integrations_google_analytics_getGAAccounts>): Promise<ResponseType<typeof api_integrations_google_analytics_getGAAccounts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-analytics/accounts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_analytics_getGAAccounts>
        }

        /**
         * Initiates Google Analytics OAuth flow.
         */
        public async getGAAuthUrl(params: RequestType<typeof api_integrations_google_analytics_getGAAuthUrl>): Promise<ResponseType<typeof api_integrations_google_analytics_getGAAuthUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-analytics/auth`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_analytics_getGAAuthUrl>
        }

        /**
         * Fetches Google Analytics data for analysis.
         */
        public async getGAData(params: RequestType<typeof api_integrations_google_analytics_getGAData>): Promise<ResponseType<typeof api_integrations_google_analytics_getGAData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/google-analytics/data`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_google_analytics_getGAData>
        }

        /**
         * Returns configuration for supported platforms.
         */
        public async getPlatformConfigs(): Promise<ResponseType<typeof api_integrations_integration_manager_getPlatformConfigs>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/integrations/platforms`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_integrations_integration_manager_getPlatformConfigs>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createScheduledJob as api_scheduler_schedule_manager_createScheduledJob,
    deleteScheduledJob as api_scheduler_schedule_manager_deleteScheduledJob,
    generateTrendComparison as api_scheduler_schedule_manager_generateTrendComparison,
    getHistoricalAnalyses as api_scheduler_schedule_manager_getHistoricalAnalyses,
    getJobExecutions as api_scheduler_schedule_manager_getJobExecutions,
    getScheduledJobs as api_scheduler_schedule_manager_getScheduledJobs,
    triggerJobExecution as api_scheduler_schedule_manager_triggerJobExecution,
    updateScheduledJob as api_scheduler_schedule_manager_updateScheduledJob
} from "~backend/scheduler/schedule-manager";

export namespace scheduler {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createScheduledJob = this.createScheduledJob.bind(this)
            this.deleteScheduledJob = this.deleteScheduledJob.bind(this)
            this.generateTrendComparison = this.generateTrendComparison.bind(this)
            this.getHistoricalAnalyses = this.getHistoricalAnalyses.bind(this)
            this.getJobExecutions = this.getJobExecutions.bind(this)
            this.getScheduledJobs = this.getScheduledJobs.bind(this)
            this.triggerJobExecution = this.triggerJobExecution.bind(this)
            this.updateScheduledJob = this.updateScheduledJob.bind(this)
        }

        /**
         * Creates a new scheduled job for automated data fetching and analysis.
         */
        public async createScheduledJob(params: RequestType<typeof api_scheduler_schedule_manager_createScheduledJob>): Promise<ResponseType<typeof api_scheduler_schedule_manager_createScheduledJob>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_createScheduledJob>
        }

        /**
         * Deletes a scheduled job.
         */
        public async deleteScheduledJob(params: { jobId: string }): Promise<ResponseType<typeof api_scheduler_schedule_manager_deleteScheduledJob>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs/${encodeURIComponent(params.jobId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_deleteScheduledJob>
        }

        /**
         * Generates a trend comparison between two analyses.
         */
        public async generateTrendComparison(params: RequestType<typeof api_scheduler_schedule_manager_generateTrendComparison>): Promise<ResponseType<typeof api_scheduler_schedule_manager_generateTrendComparison>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                currentAnalysisId:  params.currentAnalysisId,
                previousAnalysisId: params.previousAnalysisId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs/${encodeURIComponent(params.jobId)}/trend-comparison`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_generateTrendComparison>
        }

        /**
         * Retrieves historical analyses for a scheduled job.
         */
        public async getHistoricalAnalyses(params: RequestType<typeof api_scheduler_schedule_manager_getHistoricalAnalyses>): Promise<ResponseType<typeof api_scheduler_schedule_manager_getHistoricalAnalyses>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs/${encodeURIComponent(params.jobId)}/analyses`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_getHistoricalAnalyses>
        }

        /**
         * Retrieves execution history for a scheduled job.
         */
        public async getJobExecutions(params: RequestType<typeof api_scheduler_schedule_manager_getJobExecutions>): Promise<ResponseType<typeof api_scheduler_schedule_manager_getJobExecutions>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs/${encodeURIComponent(params.jobId)}/executions`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_getJobExecutions>
        }

        /**
         * Retrieves all scheduled jobs for the user.
         */
        public async getScheduledJobs(params: RequestType<typeof api_scheduler_schedule_manager_getScheduledJobs>): Promise<ResponseType<typeof api_scheduler_schedule_manager_getScheduledJobs>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_getScheduledJobs>
        }

        /**
         * Manually triggers a scheduled job execution.
         */
        public async triggerJobExecution(params: { jobId: string }): Promise<ResponseType<typeof api_scheduler_schedule_manager_triggerJobExecution>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs/${encodeURIComponent(params.jobId)}/trigger`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_triggerJobExecution>
        }

        /**
         * Updates an existing scheduled job.
         */
        public async updateScheduledJob(params: RequestType<typeof api_scheduler_schedule_manager_updateScheduledJob>): Promise<ResponseType<typeof api_scheduler_schedule_manager_updateScheduledJob>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                analysisType:      params.analysisType,
                autoAnalyze:       params.autoAnalyze,
                dayOfMonth:        params.dayOfMonth,
                dayOfWeek:         params.dayOfWeek,
                description:       params.description,
                dimensions:        params.dimensions,
                frequency:         params.frequency,
                isActive:          params.isActive,
                metrics:           params.metrics,
                name:              params.name,
                notificationEmail: params.notificationEmail,
                timeOfDay:         params.timeOfDay,
                timezone:          params.timezone,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/scheduled-jobs/${encodeURIComponent(params.jobId)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_scheduler_schedule_manager_updateScheduledJob>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
